/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import java.text.SimpleDateFormat;

/**
 * A sample validator interface for {@link OPLmetamodel.ActivityDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityDeclarationValidator {
	boolean validate();

	boolean validateDuration(OPLmetamodel.Number value);
	boolean validateEarliestStartTime(SimpleDateFormat value);
	boolean validateLatestEndTime(SimpleDateFormat value);
}
