/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import OPLmetamodel.BindingRef;
import OPLmetamodel.Expression;
import OPLmetamodel.ParameterDomain;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link OPLmetamodel.FormalParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormalParameterValidator {
	boolean validate();

	boolean validateDomain(ParameterDomain value);
	boolean validateBoundVars(EList<BindingRef> value);
	boolean validateIsOrdered(boolean value);
	boolean validateRequire(Expression value);
}
