/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import OPLmetamodel.PathExpression;
import OPLmetamodel.Reference;

/**
 * A sample validator interface for {@link OPLmetamodel.PathDereference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PathDereferenceValidator {
	boolean validate();

	boolean validateDeref(Reference value);
	boolean validateBase(PathExpression value);
}
