/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import OPLmetamodel.DefinedType;
import OPLmetamodel.Interval;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link OPLmetamodel.Sequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceValidator {
	boolean validate();

	boolean validateIntervals(EList<Interval> value);
	boolean validateTypes(DefinedType value);
}
