/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import OPLmetamodel.AbstractType;
import OPLmetamodel.Entity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link OPLmetamodel.SetType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SetTypeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateBaseType(AbstractType value);
	boolean validateElements(EList<Entity> value);
}
