/**
 *
 * $Id$
 */
package OPLmetamodel.validation;

import OPLmetamodel.Expression;
import OPLmetamodel.UnaryOp;

/**
 * A sample validator interface for {@link OPLmetamodel.UnaryExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnaryExpressionValidator {
	boolean validate();

	boolean validateExp(Expression value);
	boolean validateOp(UnaryOp value);
}
